name: "get run id"

on:
  push:
    branches:
      - "*"

  pull_request:

jobs:
  get_run_id:
    runs-on: ubuntu-latest
  
    steps:
      - name: "print"
        run: |
          echo ${{ github.run_id }}

