name: "get run id"

on:
  push:
    branches:
      - "*"

  pull_request:

jobs:
  get_run_id:
    runs-on: ubuntu-latest
  
    steps:
      - name: "print"
        run: |
          PR_NUMBER=$(echo $GITHUB_REF | awk 'BEGIN { FS = "/" } ; { print $3 }')
          echo ${{ github.run_id }}
          echo $PR_NUMBER
      - name: "curl"
        uses: wei/curl@v1
        with:
          args: -X POST https://httpbin.org/post

